### ISSUE TITLE
ANN dataset/dataloader bölümü kodlanacak

### ISSUE THREAD

**Issue by aggelen** [aggelen/1013erzincan#1]
Bir veri kümesini pytorch dataset ve dataloader nesneleri olarak tanımlayan ve özelleştiren kısım kodlanacak.

**Comment by aeguler** [comment]
Dataset kodlandı ve eğitildi . Commit: https://github.com/aggelen/1013erzincan/commit/8272ed4d59f04b1f925500843acc21e37a0815bf

**Comment by aeguler** [comment]
issue kapatılıyor.
